### ISSUE TITLE
Correlation plot containing noise

### ISSUE THREAD

**Issue by CAWarmerdam** [roshchupkin/hase#7]
Hi,

For the last weeks I have looked into HASE, and it looks like a very promising solution for high-dimensional association analyses. My initial test was trying to reproduce figure 3 from the [HASE paper](https://doi.org/10.1038/srep36076). The results has a clear diagonal for the most part, but it seems that there is also some interesting, reproducible, noise introduced as can be seen in the figure below:
![rplot2](https://user-images.githubusercontent.com/43466011/67287075-b9470d00-f4da-11e9-81e2-3941512c5a55.png)

Me and my colleagues would like to know what could possibly have caused this, so at the bottom of this issue I have described all the steps I have performed in obtaining the figure for reproducibility. We would very much appreciate If you could look into this issue.

I have made use of an up-to-date, clean clone of the HASE repository, and I used the test data that is supplied with this. All of the commands below were run within the `./test/` directory of the repository, unless indicated otherwise. I used Python 2.7.12 with the following [packages](https://github.com/roshchupkin/hase/files/3755547/packages.txt).

The commands are all according to the wiki, with the exception of the sharing process of the *individuals* folder as this folder from the converted genotype data results in the plot below, whereas the data from the **`encode_individuals`** folder appears to give correct results. Can you comment on this?
![rplot](https://user-images.githubusercontent.com/43466011/67285239-7cc5e200-f4d7-11e9-80ec-7d68f8140979.jpg)

First I have performed regular regression analysis with the commands written below:
```
$ python ../hase.py -g ./ExampleStudy/examplestudy/ -study_name example_study -o ./results -ph ./ExampleStudy/phenotype/ -cov ./ExampleStudy/covariates/ -mode regression

# Generate the output file
$ mkdir out
$ python ../tools/analyzer.py -r ./results/ -o ./out/ -df 996
```

For meta-analysis, I started with downloading the required reference panel, creating mapper files, encoding genotype and phenotype data, and calculating partial derivatives:
```
# Download the reference panel from Dropbox
../data $ wget https://www.dropbox.com/s/ffw366q4d8shfkf/1000Gp1v3.ref.gz?dl=1
../data $ wget https://www.dropbox.com/s/ajq6ngv1090splo/1000Gp1v3.ref_info.h5?dl=1

# Rename the reference panel files
../data $ mv 1000Gp1v3.ref.gz?dl=1 1000Gp1v3.ref.gz
../data $ mv 1000Gp1v3.ref_info.h5?dl=1 1000Gp1v3.ref_info.h5

# Create mapper files
$ python ../tools/mapper.py -g ./ExampleStudy/examplestudy/ -study_name example_study -o ./mapper/

# Encode the genotype and phenotype files
$ python ../hase.py -g ./ExampleStudy/examplestudy/ -study_name example_study -o ./encoded/ -mapper ./mapper/ -ph ./ExampleStudy/phenotype/ -mode encoding

# Calculate partial derivatives
$ python ../hase.py -g ./ExampleStudy/examplestudy/ -study_name example_study -ph ./ExampleStudy/phenotype/ -cov ./ExampleStudy/covariates/ -mapper ./mapper/ -o ./pd/ -mode single-meta
```

To perform meta-analysis the encoded genotype and phenotype data needs to be shared, as well as the partial derivatives, the probes folder and the individuals folder. I copied the required data to a new directory, but instead of copying the individuals folder from the converted genotype data like is described in the [wiki](https://github.com/roshchupkin/hase/wiki/HD-Meta-analysis-GWAS), I used the data from the **`encode_individuals`** folder for the reason that is described above.
```
# Make the required directories
$ mkdir -p ExampleStudy_encoded/examplestudy/genotype
$ mkdir ExampleStudy_encoded/examplestudy/individuals
$ mkdir ExampleStudy_encoded/pd_shared
$ mkdir ExampleStudy_encoded/phenotype

# Copy the required data
$ cp -r ExampleStudy/examplestudy/probes ExampleStudy_encoded/examplestudy/
$ cp -r encoded/encode_individuals/* ExampleStudy_encoded/examplestudy/individuals
$ cp -r encoded/encode_genotype/* ExampleStudy_encoded/examplestudy/genotype/
$ cp -r encoded/encode_phenotype/* ExampleStudy_encoded/phenotype/
$ cp pd/*.npy ExampleStudy_encoded/pd_shared/

# Check the resulting directory structure
./ExampleStudy_encoded $ tree
.
├── examplestudy
│   ├── genotype
│   │   ├── 0_example_study.h5
│   │   └── 1_example_study.h5
│   ├── individuals
│   │   └── example_study.h5
│   └── probes
│       └── example_study.h5
├── pd_shared
│   ├── example_study_a_cov.npy
│   ├── example_study_a_test.npy
│   ├── example_study_b_cov.npy
│   ├── example_study_C.npy
│   └── example_study_metadata.npy
└── phenotype
    └── 0_example_study.csv

6 directories, 10 files
```

Now perform meta-analysis as is written in the Wiki.
```
# Perform meta-analysis
$ python ../hase.py -g ./ExampleStudy_encoded/examplestudy/ -study_name example_study -ph ./ExampleStudy_encoded/phenotype/ -derivatives ./ExampleStudy_encoded/pd_shared/ -mapper ./mapper/ -o ./results_encoded/ -mode meta-stage

# Generate the output file
$ mkdir out_encoded
$ python ../tools/analyzer.py -r ./results_encoded/ -o ./out_encoded/ -df 996
```

I have generated the figure using the following R code, in which `args[1]` was equal to `./out/results.csv` and `args[2]` was equal to `./out_encoded/results.csv`.
```
rm(list = ls())
args <- commandArgs( trailingOnly = TRUE )

print("reading results...")
results <- read.csv(args[1], header=T, sep=" ")

print("reading results_encoded...")
results.enc <- read.csv(args[2], header=T, sep=" ")

print("merging...")
merged <- merge(results, results.enc, by=c("RSID", "phenotype"))

png("rplot.png", width = 480, height = 480)
plot(x = merged$t.stat.x, y = merged$t.stat.y, xlab="regular regression t-statistic", ylab="meta-analysis t-statistic")
dev.off()
```

**Comment by CAWarmerdam** [comment]
It has become apparent that the noise was caused partly by a duplicate variant id within the example data, which resulted in a comparison in which different regression tests with the same RSID and phenotype combinations were plotted against each other.

**Comment by roshchupkin** [comment]
@CAWarmerdam thank you for your debugging. And also apologize for the delay with reply. I am a bit busy last weeks. 

Yes, unfortunately, there is an issue with the same RSID.  The way HASE saves results, it is not possible directly separate the same RSID.  I am working on a patch for this.

**Comment by CAWarmerdam** [comment]
@roshchupkin, no problem; debugging this was fairly trivial. Great to hear that you are working on a patch that deals with duplicate RSIDs better.
As I have written at the start of this issue, I think there is a mistake in the [wiki](https://github.com/roshchupkin/hase/wiki/HD-Meta-analysis-GWAS) that explicitly states the `individuals` folder from the converted genotype data should be shared with the central site, which gives an incorrect correlation plot. Sharing the files from the `encode_individuals` folder does produce correct results. Do you agree with me?

Thank you

**Comment by roshchupkin** [comment]
Yes. You should share encode_individuals folder, that's correct I changed the wiki. Thanks!
